type Item {
    id: Int
    name: String
    price: Float
}

type Query {
    allItems: [Item!]
    item(id: Int, name: String, price: Float): Item
}

type Mutation {
    createItem(name: String!, price: Float!): Int!
}